// src/lib/routes.ts - Centralni izvor istine
export const ROUTES = {
  HOME: '/',
  INVEST: '/invest',
  INVESTMENT_GUIDE: '/investment-guide',
  CRYPTO_SHOP: '/crypto-shop',
  CLUB: '/club',
  EXCHANGE: '/exchange',
  DASHBOARD: '/dashboard',
  DEPOSIT: '/deposit',
  WITHDRAWALS: '/withdrawals',
  ACADEMY: '/academy',
  AI_INSIGHTS: '/ai-insights',
  NEURAL_DIAGNOSTICS: '/neural-diagnostics',
  ABOUT: '/about',
  TRUSTED_PARTNERS: '/trusted-partners',
  SUPPORT: '/support',
  NEWSLETTER: '/newsletter',
  TERMS: '/terms',
  PRIVACY: '/privacy',
  SECURITY: '/security',
  LOGIN: '/login',
  REGISTER: '/register',
  REGISTER_THANK_YOU: '/register/thank-you',
  MESSAGES: '/messages',
  SETTINGS: '/settings',
} as const;
